

// ============= SAMPLE DATA =============
const sampleData = [
  { vin: '5YJYGDEE1L', county: 'King', city: 'Seattle', state: 'WA', postalCode: '98122', modelYear: 2020, make: 'TESLA', model: 'MODEL Y', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 291, baseMSRP: 52000 },
  { vin: '7SAYGDEE9P', county: 'Snohomish', city: 'Bothell', state: 'WA', postalCode: '98021', modelYear: 2023, make: 'TESLA', model: 'MODEL Y', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Eligibility unknown as battery range has not been researched', electricRange: 330, baseMSRP: 54000 },
  { vin: '5YJSA1E4XK', county: 'King', city: 'Seattle', state: 'WA', postalCode: '98109', modelYear: 2019, make: 'TESLA', model: 'MODEL S', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 270, baseMSRP: 79000 },
  { vin: '5YJSA1E27G', county: 'King', city: 'Issaquah', state: 'WA', postalCode: '98027', modelYear: 2016, make: 'TESLA', model: 'MODEL S', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 210, baseMSRP: 75000 },
  { vin: '5YJYGDEE5M', county: 'Kitsap', city: 'Suquamish', state: 'WA', postalCode: '98392', modelYear: 2021, make: 'TESLA', model: 'MODEL Y', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Eligibility unknown as battery range has not been researched', electricRange: 326, baseMSRP: 53000 },
  { vin: '3FA6P0SU8H', county: 'Thurston', city: 'Yelm', state: 'WA', postalCode: '98597', modelYear: 2017, make: 'FORD', model: 'FUSION', electricVehicleType: 'Plug-in Hybrid Electric Vehicle (PHEV)', cafvEligibility: 'Not eligible due to low battery range', electricRange: 21, baseMSRP: 35000 },
  { vin: '1N4AZ0CP2D', county: 'Yakima', city: 'Yakima', state: 'WA', postalCode: '98903', modelYear: 2013, make: 'NISSAN', model: 'LEAF', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 75, baseMSRP: 29000 },
  { vin: 'KNAGV4LD9J', county: 'Snohomish', city: 'Bothell', state: 'WA', postalCode: '98012', modelYear: 2018, make: 'KIA', model: 'OPTIMA', electricVehicleType: 'Plug-in Hybrid Electric Vehicle (PHEV)', cafvEligibility: 'Not eligible due to low battery range', electricRange: 29, baseMSRP: 32000 },
  { vin: '1N4AZ0CP8F', county: 'Kitsap', city: 'Port Orchard', state: 'WA', postalCode: '98366', modelYear: 2015, make: 'NISSAN', model: 'LEAF', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 84, baseMSRP: 30000 },
  { vin: '5UXTA6C03N', county: 'King', city: 'Auburn', state: 'WA', postalCode: '98001', modelYear: 2022, make: 'BMW', model: 'X5', electricVehicleType: 'Plug-in Hybrid Electric Vehicle (PHEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 30, baseMSRP: 56000 },
  { vin: '5YJ3E1EB4L', county: 'King', city: 'Seattle', state: 'WA', postalCode: '98126', modelYear: 2020, make: 'TESLA', model: 'MODEL 3', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 322, baseMSRP: 38000 },
  { vin: '5YJ3E1EA5K', county: 'Yakima', city: 'Yakima', state: 'WA', postalCode: '98903', modelYear: 2019, make: 'TESLA', model: 'MODEL 3', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 220, baseMSRP: 40000 },
  { vin: '1N4BZ0CP4H', county: 'Thurston', city: 'Olympia', state: 'WA', postalCode: '98506', modelYear: 2017, make: 'NISSAN', model: 'LEAF', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 107, baseMSRP: 31000 },
  { vin: 'WBY1Z4C51E', county: 'King', city: 'Renton', state: 'WA', postalCode: '98059', modelYear: 2014, make: 'BMW', model: 'I3', electricVehicleType: 'Plug-in Hybrid Electric Vehicle (PHEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 72, baseMSRP: 42000 },
  { vin: '1FADP5CUXD', county: 'Yakima', city: 'Yakima', state: 'WA', postalCode: '98902', modelYear: 2013, make: 'FORD', model: 'C-MAX', electricVehicleType: 'Plug-in Hybrid Electric Vehicle (PHEV)', cafvEligibility: 'Not eligible due to low battery range', electricRange: 19, baseMSRP: 33000 },
  { vin: 'KNDCD3LD6J', county: 'King', city: 'Seattle', state: 'WA', postalCode: '98118', modelYear: 2018, make: 'KIA', model: 'NIRO', electricVehicleType: 'Plug-in Hybrid Electric Vehicle (PHEV)', cafvEligibility: 'Not eligible due to low battery range', electricRange: 26, baseMSRP: 28000 },
  { vin: 'JN1AZ0CP8C', county: 'Thurston', city: 'Tenino', state: 'WA', postalCode: '98589', modelYear: 2012, make: 'NISSAN', model: 'LEAF', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 73, baseMSRP: 32000 },
  { vin: '1FADP5CU4G', county: 'Thurston', city: 'Olympia', state: 'WA', postalCode: '98501', modelYear: 2016, make: 'FORD', model: 'C-MAX', electricVehicleType: 'Plug-in Hybrid Electric Vehicle (PHEV)', cafvEligibility: 'Not eligible due to low battery range', electricRange: 19, baseMSRP: 34000 },
  { vin: '1N4AZ1CP4J', county: 'Thurston', city: 'Olympia', state: 'WA', postalCode: '98501', modelYear: 2018, make: 'NISSAN', model: 'LEAF', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 151, baseMSRP: 30000 },
  { vin: 'WA1AAAGE4M', county: 'King', city: 'Seattle', state: 'WA', postalCode: '98108', modelYear: 2021, make: 'AUDI', model: 'E-TRON', electricVehicleType: 'Battery Electric Vehicle (BEV)', cafvEligibility: 'Clean Alternative Fuel Vehicle Eligible', electricRange: 222, baseMSRP: 66000 }
];

export default sampleData